# Generated by Django 3.0.5 on 2020-05-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0003_job_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_email', models.EmailField(max_length=254)),
                ('job_id', models.IntegerField()),
                ('stu_name', models.CharField(default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='list',
        ),
    ]
