# Generated by Django 3.0.5 on 2020-05-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0004_auto_20200509_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'resume_list',
            },
        ),
    ]
